# Generated by Django 4.2.20 on 2025-05-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_delete_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='role',
        ),
        migrations.AddField(
            model_name='apiuser',
            name='roles',
            field=models.ManyToManyField(related_name='users', to='myapp.role'),
        ),
    ]
