# Generated by Django 4.2.20 on 2025-05-04 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_apiuser_role_apiuser_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiuser',
            old_name='roles',
            new_name='role',
        ),
    ]
