# Generated by Django 4.2.20 on 2025-05-04 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_roles_apiuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='role',
        ),
        migrations.AddField(
            model_name='apiuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='myapp.role'),
        ),
    ]
